### PR TITLE
Fix/update minio version

### PR DESCRIPTION
**Pull request by shashaneRanasinghe**
Updated minio-go version to v7.0.22

### CODE REVIEW

**Review by lucasmdrs — DISMISSED** [review]

**Review by lucasmdrs — COMMENTED** [review]
hey @shashaneRanasinghe 

The changes look good :+1:  
Please address the lint issue for merging it.

It would be best to have the context being provided from other meaningful sources like the `http.Request` for example, but it might become a large PR for that.

**Comment by shashaneRanasinghe** [comment]
@lucasmdrs, could you please rerun the checks for this pull request? I encountered an error while running the linter, which reported: "E: Version '20211016ubuntu0.20.04.1' for 'ca-certificates' was not found." Unfortunately, I'm not entirely sure what caused this issue. Could you guide me through troubleshooting this problem so I can address it appropriately? Your assistance would be greatly appreciated.

**Comment by lucasmdrs** [comment]
@shashaneRanasinghe I've fixed the issue separately in #262. but for some reason this PR merge commit is not taking it in consideration :thinking:
Could you update your branch with the latest master version of Kangal (rebase/merge) or maybe push an empty commit to see if it resolves the merge commit issue?

**Review by lucasmdrs — APPROVED** [review]

**Comment by lucasmdrs** [comment]
Thank you for the contribution! :sparkle: :sparkles:

**Pull request merged**
