### PR TITLE
Include ghz support at initial readme.md

### PR DESCRIPTION
**Pull request by ldeitos**
A very little contribuition at doc.

### CODE REVIEW

**Comment by diegomarangoni** [comment]
hello @ldeitos, thanks for the contribution, we are working on fix linting, once done we will merge this

**Comment by diegomarangoni** [comment]
hey @ldeitos, could you please rebase your changes with master branch?

**Comment by ldeitos** [comment]
> hello @ldeitos, thanks for the contribution, we are working on fix linting, once done we will merge this

done!

**Review by lucasmdrs — APPROVED** [review]
:raised_hands: :heart:  Thank you @ldeitos

**Pull request merged**
